image: Ubuntu1804  # образ для сборки

stack: node 16.14.2  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

environment:
  access_token:
    secure: oUzdVnBXBt1EPfQclYxgZZSlxl+r1u2fbpOPN5IfxIlBfP2/LIAQ5iUjYFZUzkrS

deploy_script:  # скрипт развёртывания
  - git config --global credential.helper store
  - git config --global user.name AlexGnutov
  - git config --global user.email 81751916+AlexGnutov@users.noreply.github.com
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:access_token):x-oauth-basic@github.com`n" -NoNewline
  - npx push-dir --dir=build --branch=gh-pages --force --verbose
